from __future__ import annotations

from typing import Any

from config.settings import settings
from xsiam_api.client import RULE_PREFIX


def rule_name(source_id: str) -> str:
    return f"{RULE_PREFIX}{source_id}"


def source_id_from_name(name: str) -> str | None:
    if name.startswith(RULE_PREFIX):
        return name[len(RULE_PREFIX):]
    return None


def build_default_rule(source: Any) -> dict[str, Any]:
    dataset = getattr(source, "xsiam_dataset", "") or settings.xsiam_dataset
    xql = (
        f"dataset = {dataset} "
        f'| filter simulated_log_source = "{source.id}" '
        f"| comp count() as event_count by simulated_log_source "
        f"| filter event_count > 0"
    )
    return {
        "name": rule_name(source.id),
        "description": (
            f"Auto-generated by XSIAM Log Engine for simulated source "
            f"'{source.display_name}'. Safe to delete."
        ),
        "xql_query": xql,
        "severity": "informational",
        "enabled": True,
        "dataset": dataset,
    }
